### ISSUE TITLE
Potentially missing header <algorithm> in blocks.cpp

### ISSUE THREAD

**Issue by cappelletto** [aparis69/Rock-fracturing#1]
Hi,
When testing under Ubuntu 20.04, gcc/g++ v9.3.0 I get this error:
`==== Building RockFracturing (debug64) ====
blocks.cpp
../Code/Source/blocks.cpp: In static member function ‘static SDFNode* SDFUnionSphereLOD::OptimizedBVHRecursive(std::vector<SDFNode*>&, int, int, double)’:
../Code/Source/blocks.cpp:131:19: error: ‘partition’ is not a member of ‘std’
  131 |  auto pmid = std::partition(pts.begin() + begin, pts.begin() + end, BVHPartitionPredicate(stretchedAxis, axisMiddleCut));
      |                   ^~~~~~~~~
make[1]: *** [RockFracturing.make:132: obj/x64/Debug/blocks.o] Error 1
make: *** [Makefile:17: RockFracturing] Error 2
`

This can be fixed quickly by just adding `#include<algorithm>` in blocks.cpp. I think this small modification shouldn't require a pull-request, by I could do it if you find it necessary.

Cheers,
Jose

PS: Thanks for sharing this repo, I've been looking for something like this for a while without success.

**Comment by aparis69** [comment]
Hi,

Thanks for pointing this out.
The fix is now live on the repository - I will close this issue.

Hope this is useful to you :-)
Cheers,
Axel
